#!/bin/sh
### BEGIN INIT INFO
# Provides:          init-clouds-manager
# Required-Start:    reset_lgw mountvirtfs $local_fs $networking
# Required-Stop:     $local_fs
# Should-Start:      
# Should-Stop:       
# Default-Start:     02 S 2 3 4 5
# Default-Stop:      71 0 1 6
# Short-Description: 
# Description:       
#                    
#                    
### END INIT INFO

CALLED_FROM_INIT__=true

BASEDIR=$(dirname "$(readlink -f "$0")")
SCRIPT=$BASEDIR/clouds-manager.sh

# call normal script
if [ -f $SCRIPT ]; then
    . $SCRIPT
else
    exit 1
fi
